/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JniUtil */

#ifndef _Included_com_example_hellojni_JniUtil
#define _Included_com_example_hellojni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JniUtil
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_JniUtil_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
